[package]

name = "yaxpeax-pic18"
version = "0.0.1"
authors = [ "iximeow <me@iximeow.net>" ]
license = "0BSD"
repository = "http://git.iximeow.net/yaxpeax-pic18/"
description = "pic18 decoders for the yaxpeax project"

[dependencies]
yaxpeax-arch = { path = "../../yaxpeax-arch" }
"serde" = "*"
"serde_derive" = "*"

[[test]]
name = "test"
path = "test/test.rs"

[features]
default = []

use-serde = []
